### ISSUE TITLE
Reduce the code "complexity"

### ISSUE THREAD

**Issue by alisonmonteiro** [ceasbz/mzsi#2]
@cauealves Sometimes, the excess of `else if`s puts some complexity on the code (or turn it hard to read). No offense. So I think we should use something like this

```js
const data = [
  {
    sign: 'Capricorn',
    begin: [20, 1], // day and month
    end: [18, 2]  // day and month
  },
  {
    sign: 'Aquarius',
    begin: [19, 2],
    end: [20, 3]
  },
  {
    sign: 'Pisces',
    begin: [21, 3],
    end: [19, 4]
  }
];
```

And then, return the only one:
```js
let sign = data.filter(item => {
  if((day >= item.begin[0] && month === item.begin[1]) || 
    (day <= item.end[0] && month === item.end[1])) {
      return true;
  }
});
//=> { name: [ { sign: 'Capricorn', begin: [Object], end: [Object] } ] }
```

So, what do you think?
Tks!

**Comment by cauealves** [comment]
@alisonmonteiro I agree with you :)

Do you have any idea to open a pull request?

**Comment by alisonmonteiro** [comment]
Sorry, @cauealves. 
There is an idea in my comment. Did you read it?

But, if you wanna see a PR with that idea, please, let me know.
👍

**Comment by ceasbz** [comment]
@alisonmonteiro See https://github.com/ceasbz/mzsi/pull/4, what do you think? 😸

**Comment by alisonmonteiro** [comment]
Cool. Looks good to me. 🔥

**Comment by ceasbz** [comment]
@alisonmonteiro Inspired by your comment <3
